### ISSUE TITLE
0.1.58 ready for a release?

### ISSUE THREAD

**Issue by Kijewski** [strawlab/iana-time-zone#124]
Do y'all think that there is some outstanding issue? Otherwise I guess we can publish a new release.

**Comment by astraw** [comment]
I released 0.1.58 last week. https://crates.io/crates/iana-time-zone/0.1.58 Did I forget to do something?

**Comment by Kijewski** [comment]
Huh, I didn't notice. I only saw that you updated the changelog and bumped the version number. I thought I had notifications activated for new releases.
