### ISSUE TITLE
"Our MSRV is whatever `cc`'s current MSRV is"?

### ISSUE THREAD

**Issue by Kijewski** [strawlab/iana-time-zone#136]
Now that [`cc`](https://crates.io/crates/cc), maintained by the Rust Foundation itself, raises its MSRV in random intervals by some random amount, I don't think we downstream crates can provide any resemblance of a stable MSRV. Should be just adopt the policy "Our MSRV is whatever `cc`'s current MSRV is"?

**Comment by lopopolo** [comment]
Do you have a link to this policy? I'd love to learn more.

**Comment by astraw** [comment]
> Do you have a link to this policy? I'd love to learn more.

This thread https://github.com/rust-lang/cc-rs/issues/1144 eventually converges to `cc` keeping MSRV at 1.63 for some time to come. (For what it's worth, we have `cc` as a direct dependency only in `iana-time-zone-haiku`.)

Let's close this in favor of general MSRV issue at #115.
