### ISSUE TITLE
missing tag for 0.1.51 release

### ISSUE THREAD

**Issue by alex** [strawlab/iana-time-zone#73]
all the other releases have tags

**Comment by astraw** [comment]
Ah, thanks for the reminder. I just pushed [v0.1.51](https://github.com/strawlab/iana-time-zone/releases/tag/v0.1.51).

**Comment by lopopolo** [comment]
Similarly, did we cut a tag for the v0.1.0 of the haiku crate?

**Comment by lopopolo** [comment]
It also looks like 0.1.51 didn't make it into the changelog.

**Comment by astraw** [comment]
Fixed in 5572bbc7844da391c17959084ad29d811beffad9. Thanks for the reminders.
