### ISSUE TITLE
android cross builds are failing on CI with nightly rust

### ISSUE THREAD

**Issue by astraw** [strawlab/iana-time-zone#80]
Android cross builds are failing on CI with nightly rust. This started between [build 351](https://github.com/strawlab/iana-time-zone/actions/runs/3214907058) and [build 352](https://github.com/strawlab/iana-time-zone/actions/runs/3220695414) (the macOS failures were another unrelated issue #72 which has now been solved).

The key error from the CI logs seems to be:

```
aarch64-linux-android/bin/ld: cannot find -lunwind
```

**Comment by Kijewski** [comment]
My first instinct was that cross-rs accidentally uploaded a faulty docker image, but no Android image was touched in quite some time: <https://github.com/orgs/cross-rs/packages?tab=packages&q=android>.

But it looks like only `nightly` is affected. Could the error be related to <https://github.com/rust-lang/rust/issues/103175>?

**Comment by astraw** [comment]
I agree that I think the issue is nothing with changes introduced in our repository but rather that rustc nightly or cross during that time. I don't understand enough about the build process to know whether the issue you linked might be relevant. If nothing with cross changed, then indeed I think the issue is something to do with a recent rustc nightly starting about 10 October.

**Comment by astraw** [comment]
I think https://github.com/rust-lang/rust/issues/103673 is relevant here. I'm not familiar with the android development, so this is mostly beyond me.
