### ISSUE TITLE
0.1.52 appears to raise MSRV?

### ISSUE THREAD

**Issue by alex** [strawlab/iana-time-zone#82]
Building 0.1.52 appears to raise the MSRV (https://github.com/pyca/cryptography/actions/runs/3345289024/jobs/5540627366)

```
     Compiling iana-time-zone v0.1.52
       Running `rustc --crate-name iana_time_zone --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/iana-time-zone-0.1.52/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C overflow-checks=on --cfg 'feature="fallback"' -C metadata=a1f314261aac0584 -C extra-filename=-a1f314261aac0584 --out-dir /home/runner/work/cryptography/cryptography/src/rust/target/release/deps -L dependency=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps --cap-lints allow`
  error[E0658]: the `unsafe_op_in_unsafe_fn` lint is unstable
    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/iana-time-zone-0.1.52/src/lib.rs:10:1
     |
  10 | #![warn(unsafe_op_in_unsafe_fn)]
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #71668 <https://github.com/rust-lang/rust/issues/71668> for more information
```

this isn't documented in the changelog, and I don't think is intended?

**Comment by astraw** [comment]
It is definitely not intended. According to our own CI runs, the MSRV of 1.38 not causing failures with rust 1.38 on ubuntu 20.04, windows 2022 or macOS 12 ( https://github.com/strawlab/iana-time-zone/actions/runs/3342950366 ).

The commit adding that particular line is ee708f4bcfcb71b87bdf22e2208b5b9007dccf09 by @lopopolo . Could it be that erroring on unstable lints was added after 1.38 and that's why we didn't detect it with our own CI runs?

I think we can back out the lints, but we should figure out how to avoid this again.

**Comment by alex** [comment]
I wonder if this is a difference in how cargo/rust handles lints/warnings between a top-level crate and a dependency?

**Comment by astraw** [comment]
I bisected rust releases and it seems rust 1.45 through 1.51 show this error (and 1.44 and 1.52 are OK). So it is not an "MSRV" change per se as 1.38 still works but there is some range of intermediate rust versions on which this crate is broken. I guess we can just revert this particular lint and add, say, 1.48 to the CI runs to ensure we don't hit this again. Does that sound reasonable?

**Comment by alex** [comment]
Works for me. This is the first time I've seen an "MSRV works, but intermediate versions fail" issue. Fun fun fun.

Thanks!

**Comment by Kijewski** [comment]
@astraw, could you turn this commit into a PR? I created #83 that would hopefully find this kind of error in the future. It "successfully fails" for the current version: https://github.com/strawlab/iana-time-zone/actions/runs/3345648643/jobs/5541453152

**Comment by astraw** [comment]
@Kijewski I approved and merged your PR and now made https://github.com/strawlab/iana-time-zone/pull/84. If this passes the relevant parts of the CI test, you can merge it (if you approve), and we can cut a new release.

When will we get to the point of the CI configuration being more code and more complexity than the rest of the crate combined? :)

**Comment by Kijewski** [comment]
Let's pretend we are doing test-driven development, so we can increase the price of the library tenfold (0.00 € → 0.00 €). :D

**Comment by lopopolo** [comment]
@astraw we can add `-W unsafe_op_in_unsafe_fn` to the `RUSTFLAGS` env var in the lint job.

**Comment by lopopolo** [comment]
I filed this upstream:

- https://github.com/rust-lang/rust/issues/103698
