### ISSUE TITLE
Feature flag platforms

### ISSUE THREAD

**Issue by Sytten** [strawlab/iana-time-zone#88]
Currently all platforms are enabled by default and pulling their dependencies.
I recently tried upgrading to 1.0.53 and it added a bunch of things for haiku that I really don't care about since that's not a target for our software.
It would be nice to feature gate each platform.

**Comment by astraw** [comment]
This shouldn't be happening. Dependencies are pulling in only for the target being built. Can you provide steps to reproduce?

**Comment by Kijewski** [comment]
It's the same problem as in #61. Dependencies that are only needed in other platforms are still downloaded and evaluated, but they don't get compiled. That is a shortcoming of cargo that we can do nothing about.

You have to file an issue with [rust-lang/rust](https://github.com/rust-lang/cargo) if you want to see this problem fixed, but I daresay it's already known.

**Comment by Sytten** [comment]
Make sense @Kijewski. There is one exception though.
If you put the dependencies as optional and enable them with a feature flag (and default features to all platforms).

**Comment by Kijewski** [comment]
But that would break all the usages, that only indirectly depend on iana-time-zone, e.g. through chrono. IMO this bug has to be fixed in cargo itself, and working around the problem downstream does only hurts usability.

**Comment by Sytten** [comment]
Only if you don't add those feature flags in the default features no?

**Comment by Kijewski** [comment]
By default it should work everywhere, for every target platform, but maybe the number of supported platforms could be restricted by using  `no-default-features = true`.

But unless I'm mistaken, the wasm support pulls in far more dependencies than the haiku support.

**Comment by astraw** [comment]
Thanks all for the discussion. I am closing this for now.

**Comment by lopopolo** [comment]
hi @Sytten, following up here, we significantly reduced the impact of `iana-time-zone-haiku` on lockfile weight with this PR: https://github.com/strawlab/iana-time-zone/pull/106.

Let us know if this resolves your concerns!

**Comment by Sytten** [comment]
Ha thanks! I will give it is a shot. cc is acceptable as a dependency.
