### ISSUE TITLE
Replace winapi with windows-sys

### ISSUE THREAD

**Issue by Kijewski** [strawlab/iana-time-zone#90]
[Some time ago](https://github.com/strawlab/iana-time-zone/pull/35) I spoke in favor of using [winapi](https://crates.io/crates/winapi) instead of [windows-sys](https://crates.io/crates/windows-sys), because it had fewer msrv bumps, and because it was used by e.g. tokio, and chrono, so even if it was not being developed for anymore, it still had a ton of users who would hopefully notice any bugs. By now tokio has switched to windows-sys, and chrono will too in the next release. I guess it's time then to make the switch, too.

**Comment by astraw** [comment]
I support this.

**Comment by kennykerr** [comment]
Can probably close this thanks to #97 - `windows` and `windows-sys` share the underlying `windows-targets` so you should see good efficiency across `tokio`, `chrono`, etc.

**Comment by astraw** [comment]
good point.
